name = "LazyUtils"
uuid = "23a0ff22-9ace-4565-9386-b2cfba63fb2e"
authors = ["Zheng-Kai Yeh <supon3060@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
TOML = "1.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
